version: '3.8'

services:
  db:
    image: postgres:alpine # Dùng bản Alpine để tiết kiệm RAM
    container_name: magic-postgres-vps
    restart: always
    environment:
      POSTGRES_PASSWORD: phanphong123 # Đổi mật khẩu này cho an toàn
      POSTGRES_DB: MagicEnglishDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Lưu lại data kể cả khi tắt container

  backend:
    build: .
    container_name: magic-backend-vps
    restart: always
    ports:
      - "5181:8080" # Cổng ra Internet
    environment:
      # Chú ý: Host bây giờ là 'db' (tên service ở trên) chứ không phải localhost nữa
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MagicEnglishDB;Username=postgres;Password=phanphong123
      - ASPNETCORE_ENVIRONMENT=Development   
    depends_on:
      - db

volumes:
  pgdata: